#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@frpc_ext[-1]
	add ucitrack frpc_ext
	set ucitrack.@frpc_ext[-1].init=frpc_ext
	commit ucitrack
EOF

frpc=$(uci -q get frpc_ext.@frpc[-1])

if [ -z "$frpc" ]; then
	uci -q add frpc_ext frpc
fi

if [ "x$frpc" != "xmain" ]; then
	uci -q batch <<-EOF >/dev/null
		rename frpc_ext.@frpc[-1]="main"
		set frpc_ext.main.enabled="0"
		commit frpc_ext
	EOF
fi

rm -rf /tmp/luci-indexcache /tmp/luci-modulecache
exit 0
